# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

pool:
  vmImage:                         'Ubuntu-16.04'

variables:
  imageRepository:                 'dockerflaskapp'
  dockerRegistryName: 'BeckaAzureCR'
  tag: 'latest'

steps:
  - script: |
      if [ -f docker-compose.test.yml ]; then
        docker-compose --file docker-compose.test.yml build
        docker-compose --file docker-compose.test.yml run sut
      fi
    displayName: 'Run tests'
  
  - task: Docker@2
    displayName: 'Build Docker image'
    inputs:
      containerRegistry: $(dockerRegistryName)
      repository: $(imageRepository)
      command: 'build'
      Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'

  - task: Docker@2
    displayName: 'Push Docker Image to Container Registry'
    inputs:
      containerRegistry: $(dockerRegistryName)
      repository: $(imageRepository)
      command: push