# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  imageRepository:                 'dockerflaskapp'
  dockerRegistryName: 'BeckaAzureCR'
  tag: 'latest'

stages:
- stage: Build
  displayName: Build and Deploy image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Build an image'
      inputs:
        containerRegistry: $(dockerRegistryName)
        repository: $(imageRepository)
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    - task: Docker@2
      displayName: 'Push an image'
      inputs:
        containerRegistry: $(dockerRegistryName)
        repository: $(imageRepository)
        command: push