####################################################
# Docker example for Actions                       #
####################################################

name:                   Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:           [ master ]

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  pull_request:
    branches:           [ master ]

env:
  # Change variables to your repo and image name - must be lowercase and set in the format OWNER/REPOSITORY/IMAGE_NAME
  IMAGE_REPOSITORY:     owner/repository
  IMAGE_NAME:           your-image-name


jobs:
  # Optional - Run tests
  test:
    runs-on:            ubuntu-latest

    steps:
      - uses:           actions/checkout@v2

      - name:           Run tests
        run:            |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          fi

  # Build image and push to GitHub Packages.
  push:
    runs-on:            ubuntu-latest

    steps:
      - if:             github.ref == 'refs/heads/master' && github.event_name == 'push'
        name:           Checkout the repo
        uses:           actions/checkout@v2
        
      - if:             github.ref == 'refs/heads/master' && github.event_name == 'push'
        name:           Push to GitHub Packages
        uses:           docker/build-push-action@v1
        with:
          username:     ${{ github.actor }}
          password:     ${{ secrets.GITHUB_TOKEN }}
          registry:     docker.pkg.github.com
          repository:   ${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}
          tag_with_ref: true
